import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import Needhelp from "@/components/NeedHelp/Needhelp";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="mt-10 xl:mt-0">
          {children}
        </div>
        {/* <Needhelp /> */}
        <Footer />
      </body>
    </html>
  );
}
